# Netlify configuration file

# Enable client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build settings
[build]
  command = "npm run build"
  publish = "dist"

# Environment variable configuration
[build.environment]
  NODE_VERSION = "18"

# Headers to enable SPA routing
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app *.supabase.co *.googleapis.com *.gstatic.com *.youtube.com *.glokalizm.com; img-src 'self' data: blob: *.netlify.app *.supabase.co *.glokalizm.com *.unsplash.com *.placehold.co; connect-src 'self' *.netlify.app *.supabase.co;"